// This file is auto-generated by @hey-api/openapi-ts

export type AuthSource = 'google';

export type IUser = {
    id: number;
    email: string;
    firstName: string;
    lastName: string;
    authSource: AuthSource;
};

export type IChallenge = {
    id: number;
    title: string;
    description: string;
    author: IUser;
    series: Array<IChallengeSeries>;
    version: number;
    versionCreatedAt: string;
    versionAuthor: IUser;
    createdAt: string;
    updatedAt: string;
};

export type IChallengeSeries = {
    id: number;
    title: string;
    description: string;
    challenges: Array<IChallenge>;
    author: IUser;
    version: number;
    versionCreatedAt: string;
    versionAuthor: IUser;
    createdAt: string;
    updatedAt: string;
};

export type GetChallengesResponse = Array<IChallenge>;

export type GetChallengesError = unknown;

export type CreateChallengeData = {
    body: {
        seriesId?: number | null;
        description: string;
        title: string;
    };
};

export type CreateChallengeResponse = IChallenge;

export type CreateChallengeError = unknown;

export type GetSeriesResponse = Array<IChallengeSeries>;

export type GetSeriesError = unknown;

export type CreateChallengeSeriesData = {
    body: {
        description: string;
        title: string;
    };
};

export type CreateChallengeSeriesResponse = IChallengeSeries;

export type CreateChallengeSeriesError = unknown;

export type $OpenApiTs = {
    '/challenges': {
        get: {
            res: {
                /**
                 * Ok
                 */
                '200': Array<IChallenge>;
            };
        };
        post: {
            req: CreateChallengeData;
            res: {
                /**
                 * Ok
                 */
                '200': IChallenge;
            };
        };
    };
    '/challenges/series': {
        get: {
            res: {
                /**
                 * Ok
                 */
                '200': Array<IChallengeSeries>;
            };
        };
        post: {
            req: CreateChallengeSeriesData;
            res: {
                /**
                 * Ok
                 */
                '200': IChallengeSeries;
            };
        };
    };
};